version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: bdcontainer
    ports:
      - 3307:3306
      - 33061:33060
    environment:
      - MYSQL_ROOT_PASSWORD=pass2024
    networks:
      - mysql_phpmyadmin
    volumes:
      - volume_mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: bdguicontainer
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=pass2024
    networks:
      - mysql_phpmyadmin
    depends_on:
      - mysql

networks:
  mysql_phpmyadmin:
    driver: bridge

volumes:
  volume_mysql:
